import fg from "fast-glob";
import fs from "fs";
import path from "path";
import { iconColors, iconSizes } from "../config.js";

const ICONS_DIR = path.resolve("src/icons");
const COMPONENTS_DIR = path.resolve("src/components");

const DIST_DIR = path.resolve("dist");
const DIST_ICONS_DIR = path.join(DIST_DIR, "icons");
const DIST_COMPONENTS_DIR = path.join(DIST_DIR, "components");

const CSS_OUTPUT_FILE = path.join(DIST_DIR, "icons.css");
const SCSS_OUTPUT_FILE = path.join(DIST_DIR, "icons.scss");
const MINIFIED_CSS_OUTPUT_FILE = path.join(DIST_DIR, "icons.min.css");
const OUTPUT_TS_FILE = path.join(DIST_DIR, "getIcon.ts");

const getIconNames = async () => {
  const entries = await fg("**/*.svg", { cwd: ICONS_DIR });

  return entries.map((entry) =>
    entry.replace(/\.svg$/, "").replace(/\\/g, "/")
  );
};

const cleanDist = () => {
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
    return;
  }

  for (const entry of fs.readdirSync(DIST_DIR)) {
    const entryPath = path.join(DIST_DIR, entry);
    fs.rmSync(entryPath, { recursive: true, force: true });
  }
};

const copyIcons = async () => {
  const files = await fg("**/*.svg", { cwd: ICONS_DIR });

  for (const file of files) {
    const src = path.join(ICONS_DIR, file);
    const dest = path.join(DIST_ICONS_DIR, file);

    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
  }
};

const copyComponents = async () => {
  const files = await fg("**/*", { cwd: COMPONENTS_DIR, dot: true }); // dot: true to include hidden files

  for (const file of files) {
    const src = path.join(COMPONENTS_DIR, file);
    const dest = path.join(DIST_COMPONENTS_DIR, file);

    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
  }
};

const createIconsCSS = (icons) => {
  const iconClassNames = icons.map((icon) => `.ic-${icon}`).join(",\n");
  const sharedCSS = `${iconClassNames} {
  background-position: center;
  background-repeat: no-repeat;
  display: inline-block;
  height: 24px;
  width: 24px;
}`;
  const iconSpecificCSS = icons
    .map((icon) => {
      const svgUrl = `./icons/${icon}.svg`;
      return `.ic-${icon} {
  background-image: url('${svgUrl}');
  mask: url('${svgUrl}') no-repeat center / contain;
  -webkit-mask: url('${svgUrl}') no-repeat center / contain;
}`;
    })
    .join("\n\n");

  const iconSizesCSS = iconSizes
    .map((iconSize) => {
      return `.icon-size-${iconSize} {
  background-size: contain;
  width: ${iconSize}px;
  height: ${iconSize}px;
}`;
    })
    .join("\n\n");

  // {a:1, b:2}  ==>  [[a,1],[b,2]]

  const iconColorsCSS = Object.entries(iconColors)
    .map(([colorName, colorValue]) => {
      return `.icon-color-${colorName} {
  filter: ${colorValue};
  background-image: unset;
  background-color: ${colorValue};
}`;
    })
    .join("\n\n");

  const cssString =
    sharedCSS +
    "\n\n" +
    iconSpecificCSS +
    "\n\n" +
    iconSizesCSS +
    "\n\n" +
    iconColorsCSS;
  return cssString;
};

const minifyCSS = (css) => {
  return css
    .replace(/\s+/g, " ") // collapse whitespace
    .replace(/\s*([{}:;,])\s*/g, "$1") // remove space around CSS symbols
    .replace(/;}/g, "}") // remove unnecessary semicolons
    .trim();
};

const createGetIconTS = (icons) => {
  const iconMapEntries = icons
    .map((icon) => `  '${icon}': 'ic-${icon}'`)
    .join(",\n");

  const sizes = iconSizes.join(", ");
  const colors = Object.keys(iconColors)
    .map((iconColor) => `'${iconColor}'`)
    .join(", ");
  return `// Auto-generated by build script. Do not edit manually.

export const iconSet = {
${iconMapEntries}
} as const;

export const iconSizes = [${sizes}] as const
export const iconColors = [${colors}] as const

export type IconName = keyof typeof iconSet
export type IconClassName = typeof iconSet[IconName]
export type IconSize = typeof iconSizes[number]
export type IconColor = typeof iconColors[number]

export function getIcon(iconName: IconName): IconClassName {
  if (!iconSet[iconName]) {
    console.warn(\`icon \${iconName} does not exist in the icon set\`)
    return 'INVALID_ICON' as IconClassName;
  }
  return iconSet[iconName];
}
`;
};

export async function build() {
  try {
    const iconNames = await getIconNames();
    cleanDist();
    await copyIcons();
    await copyComponents();
    const css = createIconsCSS(iconNames);
    fs.writeFileSync(CSS_OUTPUT_FILE, css, "utf-8");
    fs.writeFileSync(SCSS_OUTPUT_FILE, css, "utf-8");
    fs.writeFileSync(MINIFIED_CSS_OUTPUT_FILE, minifyCSS(css), "utf-8");
    const tsContent = createGetIconTS(iconNames);
    fs.writeFileSync(OUTPUT_TS_FILE, tsContent, "utf-8");
  } catch (err) {
    console.error("❌ Build failed: \n", err);
    process.exit(1);
  }
}

build();
