name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

      # STRAPI
      DATABASE_CLIENT: sqlite
      DATABASE_SSL: false
      DATABASE_FILENAME: .tmp/data.db

      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      APP_KEYS: ${{ secrets.APP_KEYS }}
      API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
      ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
      TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CONTENT_ENCRYPTION_KEY: ${{ secrets.CONTENT_ENCRYPTION_KEY }}

      # ASTRO
      # no need to set ASSET_URL now since assets are copied over to Astro
      CMS_URL: http://localhost:1337
      # BASE_PATH: /portfolio-remake # only necessary when deploying with a path as base

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Strapi
        run: pnpm build --ui=stream

      - name: Import Strapi content
        run: pnpm --filter @repo/cms import-content

      - name: Build static site
        run: pnpm build-static

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/astro/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
