name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

      DATABASE_CLIENT: sqlite
      DATABASE_SSL: false
      DATABASE_FILENAME: .tmp/data.db

      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      APP_KEYS: ${{ secrets.APP_KEYS }}
      API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
      ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
      TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CONTENT_ENCRYPTION_KEY: ${{ secrets.CONTENT_ENCRYPTION_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Strapi
        run: pnpm build --ui=stream

      - name: Import Strapi content
        run: pnpm --filter @repo/cms import-content

      - name: Build static site
        run: pnpm build-static
